Check if can progress past the laminas dependency issue
Error: laminas/laminas-dependency-plugin contains a Composer plugin which is blocked by your allow-plugins config. You may add it to the list if you consider it safe.

What we had looked to be what was required. Allowing all to see if that works for now